### ISSUE TITLE
v4.0 wrapAround lag

### ISSUE THREAD

**Issue by webyonet** [FormidableLabs/nuka-carousel#309]
Enabling wrapAround shows a blank slide after the last item in the dynamic list

![ezgif com-resize](https://user-images.githubusercontent.com/973302/37554103-1a7a90c8-29e5-11e8-910b-8cfda8c76b80.gif)

```
class App extends React.Component {
    constructor() {
        super(...arguments);
        this.state = { slideIndex: 0, length: 6 };
    }

    get colors() {
        return ['7732bb', '047cc0']; //list
    }

    render() {
        return (
            <div style={{ width: '50%', margin: 'auto' }}>
                <Carousel
                    autoplay={true}
                    wrapAround={true}
                    slideIndex={this.state.slideIndex}
                    afterSlide={slideIndex => this.setState({ slideIndex })}
                    renderTopCenterControls={({ currentSlide }) => (
                        <div style={{ fontFamily: 'Helvetica', color: '#fff' }}>
                            Nuka Carousel: Slide {currentSlide + 1}
                        </div>
                    )}
                >
                    {this.colors.map((color, index) => ( //dynamic render
                        <img
                            src={`http://placehold.it/1000x400/${color}/ffffff/&text=slide${index + 1}`}
                            key={color}
                        />
                    ))
                    }
                </Carousel>
            </div>
        );
    }
}
```

**Comment by ovaldi** [comment]
+1

**Comment by aaronlifton2** [comment]
seems to also be a problem for > 2 slides
![image](https://user-images.githubusercontent.com/21133757/37740312-7f049e20-2d1a-11e8-8fbc-a680f463859a.png)

**Comment by michaek** [comment]
It does not appear that #310 addressed this issue. This is what I'm seeing (with two slides, `wrapAround: true`):

1. Show slide 1
2. Transition to slide 2
3. Transition to slide 1
4. Slide 1 disappears
...

At step 4, it appears that the container is restored to `transform: translate3d(0,0,0)` but slide 1 is not restored to `left: 0`, so it remains "offscreen".

**Comment by evgeni-tsn** [comment]
Same issue v4.0.1

**Comment by carlospaelinck** [comment]
![wrap-around](https://user-images.githubusercontent.com/1738349/37880188-3dd95048-304a-11e8-9a89-30d920f81e6a.gif)

Nuka 4.0.0 did have a bug with wrap around and a carousel with slides. That has been addressed with 4.0.1 and shown in the above gif both using the button and swipe controls. If there are still issues a code example would be great so we can test it out!

**Comment by michaek** [comment]
@carlospaelinck I'm definitely still seeing this in 4.0.1, and the comment directly above yours reports the same. I'll provide an example tomorrow, but I definitely think this is marked closed prematurely.

**Comment by ovaldi** [comment]
Same issue v4.0.1 +1

**Comment by webyonet** [comment]
this lag is still happening on v4.0.1

**Comment by michaek** [comment]
@carlospaelinck The demo that ships with nuka-carousel is manually managing slideIndex. If you comment out the code that's setting slideIndex, this is immediately reproducible in the demo:

```
          wrapAround={this.state.wrapAround}
          // slideIndex={this.state.slideIndex}
          // afterSlide={slideIndex => this.setState({ slideIndex })}
          renderTopCenterControls={({ currentSlide }) => (
```

That suggests that a short-term consumer workaround would be to implement an `afterSlide` when using nuka-carousel, but it should probably be considered a bug that it's necessary to do so.

**Comment by carlospaelinck** [comment]
Ok, so the issue is exclusive of two slides but rather when running uncontrolled. We have a new issue here to track this: https://github.com/FormidableLabs/nuka-carousel/issues/315.

PR #310 did fix the issue for wrap around with two slides when controlled from a parent component.
