### ISSUE TITLE
Initial height is broken

### ISSUE THREAD

**Issue by balazsorban44** [FormidableLabs/nuka-carousel#417]
### Describe Your Environment

- What version of nuka-carousel are you using? latest
- What version of React are you using? latest
- What browser are you using? chrome
- What machine are you on? linux

### Describe the Problem

**Expected behavior:** [What you expect to happen]
That the initial height is the first (or the tallest) image's height
**Actual behavior:** [What actually happens]
No matter what I set, the initial height is 100px
Example:
[![Edit o58601znvq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o58601znvq)
### Additional Information
I wrote about this at the issue #413 but I move it into a new issue for clearance.

> When the carousel first loads, it is only 100px high, no matter what I set where. Changing to the next slide, or resizing the window, everything snaps into place, and the height becomes the image's height as it is supposed to be.

**Comment by ashika01** [comment]
@balazsorban44 : we absorb the behavior only in Sandbox and not when you install and run the package in a browser. Could you let us know if you face the issue outside CodeSandbox?

**Comment by dennis3124** [comment]
Same issue, the initial height is always miscalculated for some reason. Once i slide to the next slide, it readjusts correctly

**Comment by synekdok** [comment]
Might be useful for some - here's a veeeery hacky workaround I've been using to get the carousel to the correct height without having to interact with it first

```
componentDidMount(){
    setTimeout(() => {
        try {
            this._carousel.setDimensions(null)
        }
        catch(err){
                // sometimes it crashes in chrome, pristine error handling here
        }
    }, 200);
}
```

**Comment by balazsorban44** [comment]
@synekdok Since more of us has the same problem, I don't feel that we should make hacks to solve it, rather implement the solution directly in this package!

**Comment by NubSoup** [comment]
Also, when using in modal position fixed, height/width 100%.  and using image ratio % trick.  slides are rendering at 20px height on first load until resize is triggered. Also it only resizes properly when it's the width that changes in the resize, not height.  

need to address resizing height properly when height changes and width does not.

example code:
https://codesandbox.io/s/j4n5046k7w

**Comment by edwinharly** [comment]
In my case, the initial height is 0,

[![Edit pkx5p4jj9x](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pkx5p4jj9x)

**Comment by ianregister** [comment]
Explicitly setting the image width and height attributes fixed this for me. However this is totally an issue in a production site with v4.3.7

https://codesandbox.io/s/9zy4nz3684

**Comment by NubSoup** [comment]
> Explicitly setting the image width and height attributes fixed this for me. However this is totally an issue in a production site with v4.3.7
> 
> https://codesandbox.io/s/9zy4nz3684

Are you using percentages or px values? I believe this is still an issue for percentages for those that want to use a more responsive approach.

**Comment by ryanwalters** [comment]
Taking a look at this trace:
```
findMaxHeightSlide      @ index.js:794
getSlideHeight          @ index.js:815
calcSlideHeightAndWidth @ index.js:830
setDimensions           @ index.js:874
componentDidMount       @ index.js:180
```

We see that we're getting to this function:
```js
  findMaxHeightSlide(slides) {
    let maxHeight = 0;
    for (let i = 0; i < slides.length; i++) {
      if (slides[i].offsetHeight > maxHeight) {
        maxHeight = slides[i].offsetHeight;
      }
    }
    return maxHeight;
  }
```

But `slides` is an empty NodeList, which is causing `maxHeight` to be 0.

**Comment by ryanwalters** [comment]
Those line numbers are from the production build version in the node_modules folder. Should have specified that, my bad.

**Comment by cwahlfeldt** [comment]
I seem to be having a similar issue as this but my initial height is huge (1286px). Cant seem to change it either with `initialSlideHeight`.

**Comment by rdgomt** [comment]
Same issue here

**Comment by alaskaa** [comment]
Same issue here. When images get loaded from an API, the height is always auto/100px. InitialSlideHeight and heightMode are both not working when they're set. 

We had to trigger a resize event on load for our ImageArray to get it to work, which is not really ideal but at least it works for now. Keen to hear when this gets fixed too!

**Comment by ianregister** [comment]
I was able to resolve for a full screen responsive image carousel by measuring the image size based on the screen size and then merging the height into the settings array for initialSlideHeight. Weirdly as a px value rather than integer. This meant I did not need to do any resize events. I'll put a codepen example up when I get a chance.

**Comment by alvinsight** [comment]
Same issue here 👍

**Comment by ChristiaanScheermeijer** [comment]
I'm also experiencing this issue when rendering Tiles that maintain a given aspect ratio.

The problem is the order of width/height calculation. In the initial render each slides gets a width of `0px`. This is causing the height being miscalculated when using heightMode `first` or `max`. 

I solved it by calculating and setting the width first. Then in the setState callback the height gets calculated and set.

**Comment by omasback** [comment]
@ChristiaanScheermeijer this sounds like the exact same buggy behavior that I reported, which they thought they fixed. https://github.com/FormidableLabs/nuka-carousel/issues/202

**Comment by haugan** [comment]
For a temporary fix that works in IE, Firefox, and Chrome - set `public async componentDidUpdate() {
        setTimeout(() => {
            window.dispatchEvent(new Event('resize'));
        }, 0);
    }` in the component that holds Carousel, then set Carousel's initialSlideWitdh to some pixel value `initialSlideWidth={'300px'}`. At least that worked for me!

**Comment by omar-complex** [comment]
I have the same issue. Any updates?

**Comment by vyteniskuciauskas-home24** [comment]
Manually triggering resize event fixes the issue :/

**Comment by vyteniskuciauskas-home24** [comment]
Solution use reference to module and initiate resize
https://codesandbox.io/s/5xlw1x7jv4

**Comment by sarmeyer** [comment]
fixed with #469

**Comment by jamesmosier** [comment]
@sarmeyer Was there anything else needed for #469 to fix this issue (i.e. any requirements when calling the component)? I'm on version `4.5.3` but still see the `ul.slider-list` element having 18px height on load (initial load is fine, but when I re-render a slider with new images then the height is 18px).
