### ISSUE TITLE
Can't swipe slider with mouse in Safari

### ISSUE THREAD

**Issue by onceSoared** [FormidableLabs/nuka-carousel#599]
**Environment:** Safari Version 13.0.2 
**Steps to reproduce:**
1. Open [(http://kenwheeler.github.io/nuka-carousel/#/)](url)
2. Try to swipe with mouse
3. Image dragging, impossible to swipe

**Comment by sarmeyer** [comment]
Hi @onceSoared - thanks for submitting this issue. We previously came across this problem and added a fix for it, but it seems to have been lost over the last few releases. I'll make sure it gets out in the next release, probably tomorrow or Wednesday!

**Comment by sarmeyer** [comment]
fixed in the latest release! 🙌

**Comment by kanav4** [comment]
swiping left and right with mouse is still not working
can you please provide me with the solution for this
