### ISSUE TITLE
Fix Speed Slide Flicker and `wrapAround`

### ISSUE THREAD

**Issue by buzzguy** [FormidableLabs/nuka-carousel#654]
# Bugs and Questions
When swiping between slides when `wrapAround` prop is set, it sometimes jumps to the next slide without a smooth transition.

### Describe Your Environment

- What version of nuka-carousel are you using? 4.6.1
- What version of React are you using? 16.8.1
- What browser are you using?chrome
- What machine are you on?mac

### Describe the Problem
Swiping between slides when the `wrapAround` prop is set to true, I'm getting the same issue that https://github.com/FormidableLabs/nuka-carousel/pull/508 seemed to have addressed

1. Create a public minimal repository that we can `git clone`, with install + error reproduction steps in the README.
https://github.com/buzzguy/test-carousel

**Expected behavior:** [What you expect to happen]
Smooth transition between slides when swiping backwards and forwards
**Actual behavior:** [What actually happens]
jump skips between slides when `wrapAround` is set, but looks fine without it

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by TimmJensen** [comment]
Same issue. :(

**Comment by harterc1** [comment]
I have the same issue.  The lack of a smooth transition when swiping gives a "low quality" user experience.

**Comment by amaidah** [comment]
Indeed, the sudden jumping does not feel very "luxury".

**Comment by darklight9811** [comment]
Any updates to this?

**Comment by feather-alex** [comment]
Came here to say this has now been fixed with #676 and released in v4.6.6! Thanks for all the hard work @halitogunc and for the great job maintaining this repo @sarmeyer. It doesn't go unnoticed!

**Comment by darklight9811** [comment]
The flicker is gone but it's still kinda weird related to the normal carousel (without wrapAround). But thanks for the hard work.

**Comment by falafeljan** [comment]
the issue persists for me when both swiping via touch events or changing `slideIndex` externally.

**Comment by emmad5** [comment]
This issue persists for me when using the dots to navigate slides
for example on the given sandbox if you change `wrapAround` to true and then use the dots to navigate to the last slide it flickers white before showing the slide
https://codesandbox.io/s/currying-smoke-c8v2n?fontsize=14&hidenavigation=1&theme=dark

**Comment by valeriandigital** [comment]
On the last version it still missing drug smooth animation and proper transition time with wrapAround enabled.
