### ISSUE TITLE
Can't scroll to the last items on the right when slidesToScroll={3}

### ISSUE THREAD

**Issue by gkrinc** [FormidableLabs/nuka-carousel#96]
When I have a carousel with 9 slides and the following settings, I can't seem to scroll to the last 2 items on the right. I get the elastic effect and the highest currentSlide will go is 6. If I set slideIndex to 8 in the settings currentSlide is 8 and I can scroll to 7, then 6, but once I'm at 6 I can't go back to 7 or 8.

```
var settings = {
       slidesToShow: 3,
       slidesToScroll: 1,
       cellAlign: 'center',
       cellSpacing: 0,
       slideWidth: 1,
       easing: 'easeInOut',
       decorators: null,
       slideIndex: 2
};
```

If I change the slidesToShow to 1 I can get to all of the slides; currentSlide will go up to 8.

Here's the state when currentSlide is 0 and 6
![screen shot 2016-06-07 at 4 43 12 pm](https://cloud.githubusercontent.com/assets/2718382/15874064/80f7c1c8-2ccf-11e6-8e43-2b9a870b9853.png)
![screen shot 2016-06-07 at 4 43 50 pm](https://cloud.githubusercontent.com/assets/2718382/15874065/80f8a886-2ccf-11e6-9d72-cbe7cc9f5ad3.png)

Using v1.2.1

**Comment by kenwheeler** [comment]
Can you try with master?

**Comment by gkrinc** [comment]
Still not working on master (2.0.1) and I ended up with a few other visual bugs

**Comment by gkrinc** [comment]
@kenwheeler, can you point me to a spot in the code where I could debug in my setup? I assume it has something to do with a bounds calculation of the last slide index or something along those lines.

**Comment by mouhsinelonly** [comment]
+1 does not drag to last item

**Comment by awhitehouse104** [comment]
This seems to be a problem with any number other than 1, not just 3

**Comment by awhitehouse104** [comment]
Fixed this in [pr #110 0](https://github.com/kenwheeler/nuka-carousel/pull/110) for anyone interested

**Comment by gkrinc** [comment]
Definitely related to slidesToShow > 1 and cellAlign = 'center' in my case.

**Comment by ACPrice** [comment]
@kenwheeler Is this likely to be merged soon? I'm encountering this issue.

**Comment by mdaxtman** [comment]
fixed with PR #159

**Comment by gkrinc** [comment]
Not sure what happened with the merge for 2.0.3, but the problem persists. PR #159 had helped a bit, letting me at least scroll to (center) the 8th of 9 slides, but now I'm back to the problem of only being able to scroll to (center) the 7th of 9 slides. I tried scrollMode 'page' and 'reminder'.

Gotta stick with my fork for now: https://github.com/gkrinc/nuka-carousel

**Comment by mdaxtman** [comment]
@gkrinc sorry for the inconvenience, we haven't bumped the version for `npm` yet. We're going to work out a few more bugs before we do that. As a result, npm is still downloading a release from August. However, the changes that were merged into `master` seem to be working fine for me locally when I replicate your settings and number of children. Let me know if this looks right for your use case-- 

```
return (
      <div>
        <Carousel
          slidesToShow={3}
          slidesToScroll={1}
          cellAlign='center'
          scrollMode='page'
          ref="carousel"
          data={this.setCarouselData.bind(this, 'carousel')}
          slideIndex={this.state.slideIndex}
          afterSlide={newSlideIndex => this.setState({ slideIndex: newSlideIndex })}>
          <img src="http://placehold.it/1000x400&text=slide1"/>
          <img src="http://placehold.it/1000x400&text=slide2"/>
          <img src="http://placehold.it/1000x400&text=slide3"/>
          <img src="http://placehold.it/1000x400&text=slide4"/>
          <img src="http://placehold.it/1000x400&text=slide5"/>
          <img src="http://placehold.it/1000x400&text=slide6"/>
          <img src="http://placehold.it/1000x400&text=slide7"/>
          <img src="http://placehold.it/1000x400&text=slide8"/>
          <img src="http://placehold.it/1000x400&text=slide9"/>
        </Carousel>
      </div>
    )
```
with those settings I get this--

<img width="755" alt="screen shot 2016-11-24 at 11 54 26 am" src="https://cloud.githubusercontent.com/assets/8061227/20609054/d0f39b0a-b23c-11e6-8fa2-89960849c8e6.png">

Regardless of whether we get this figured out for you, due to the npm versioning it may be best to stick with your fork for now, unless you want to hardcode the `nuka-carousel` master branch in your `package.json` (probably not recommended).

**Comment by gkrinc** [comment]
Thanks @mdaxtman. Got an idea when the next version will be released?

**Comment by mdaxtman** [comment]
@gkrinc. No problem. I'm not sure, but soon. Sometime next week would be my guess.
